version: '3.7'
services:
  # Load Balancer (Entry Point)
  gateway.local.zthunworks.com:
    image: zthun/works.proxy:1.0.0
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    depends_on:
      - gateway-services-api
      - gateway-services-web
    volumes:
      - ./packages/gateway.proxy/conf.d:/etc/nginx/conf.d
  # Node Ports
  gateway-services-web:
    image: node:16.6.0
    volumes:
      - .:/usr/dev
    working_dir: /usr/dev
    command: npm --workspace @zthun/gateway.web run debug

  gateway-services-api:
    image: node:16.6.0
    ports:
      - 9229:9229
    volumes:
      - .:/usr/dev
    working_dir: /usr/dev
    command: npm --workspace @zthun/gateway.api run debug
    depends_on:
      - gateway-databases-vault
    environment:
      - DATABASE_URL=mongodb://gateway-databases-vault:27017
  # Databases
  gateway-databases-vault:
    image: mongo:4.2.0
  # Database Helpers
  gateway-databases-vault-access:
    image: mongo-express:0.49
    ports:
      - 8081:8081
    depends_on:
      - gateway-databases-vault
    environment:
      - ME_CONFIG_MONGODB_SERVER=gateway-databases-vault
  # Mock Apps
  roadblock-services-api:
    image: zthun/works.api:1.4.0
  legal-services-api:
    image: zthun/works.api:1.4.0
  support-services-api:
    image: zthun/works.api:1.4.0
