version: '3.7'
services:
  # Load Balancer (Entry Point)
  gateway.local.zthunworks.com:
    image: zthun/works.proxy:1.0.0
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    depends_on:
      - gateway-services-api
    volumes:
      - ./packages/gateway.proxy/conf.d:/etc/nginx/conf.d
  # Node Ports
  gateway-services-api:
    image: node:16.6.0
    ports:
      - 9229:9229
    volumes:
      - .:/usr/dev
    working_dir: /usr/dev
    command: npm --workspace @zthun/gateway.api run debug
