services:
  # Load Balancer (Entry Point)
  legal.local.zthunworks.com:
    image: zthun/works.proxy:1.0.0
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    depends_on:
      - shared-services-api
      - terms-services-web
    volumes:
      - ./packages/legal.proxy/conf.d:/etc/nginx/conf.d
  # Node Ports
  terms-services-web:
    image: node:16.6.0
    volumes:
      - .:/usr/dev
    working_dir: /usr/dev
    command: npm --workspace @zthun/terms.web run debug
  shared-services-api:
    image: zthun/works.server:3.0.0
    depends_on:
      - zthunworks-services-users
      - zthunworks-services-vault
      - zthunworks-services-notifications
      - zthunworks-services-cookies
      - zthunworks-services-apps
  zthunworks-services-users:
    image: zthun/works.users:3.0.1
    environment:
      - DATABASE_URL=mongodb://legal-database:27017
    depends_on:
      - legal-database
  zthunworks-services-vault:
    image: zthun/works.vault:3.0.1
    environment:
      - DATABASE_URL=mongodb://legal-database:27017
    depends_on:
      - legal-database
  zthunworks-services-notifications:
    image: zthun/works.notifications:3.0.0
  zthunworks-services-cookies:
    image: zthun/works.cookies:3.0.0
  zthunworks-services-apps:
    image: zthun/works.apps:3.0.1
  roadblock-services-web:
    image: zthun/roadblock.web:latest
  roadblock-services-api:
    image: zthun/roadblock.api:latest
  # Databases
  legal-database:
    image: mongo:4.2.0
  # Utilities
  database.zthunworks.com:
    image: mongo-express:0.49
    depends_on:
      - legal-database
    environment:
      - ME_CONFIG_MONGODB_SERVER=legal-database
  smtp.zthunworks.com:
    image: rnwood/smtp4dev:v3.1
