version: 2.1

workflows:
  check-build:
    jobs:
      - analyze
      - test
      - build

jobs:
  analyze:
    docker:
      - image: node:17.2.0
    steps:
      - checkout
      - run:
          name: Install Packages
          command: 'yarn install'
      - run:
          name: Lint Application Files
          command: 'yarn lint'
  build:
    docker:
      - image: node:17.2.0
    steps:
      - checkout
      - run:
          name: Install Packages
          command: 'yarn install'
      - run:
          name: Build Applications
          command: 'yarn build'
