version: 2.1

executors:
  node:
    docker:
      - image: node:17.2.0

workflows:
  make:
    jobs:
      - setup
      - analyze:
          requires:
            - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - setup

jobs:
  setup:
    executor: node
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
  analyze:
    executor: node
    steps:
      - run:
          name: Analyze Source Code
          command: yarn lint
  test:
    executor: node
    steps:
      - run:
          name: Test Application
          command: yarn test
      - store_artifacts:
          path: reports/coverage
  build:
    executor: node
    steps:
      - run:
          name: Build Application
          command: yarn build
