version: 2.1

jobs:
  setup:
    machine: true
    steps:
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - checkout
      - run:
          name: Setup Dependencies
          command: docker build . --target setup
      - persist_to_workspace:
          root: .
          paths:
            - .

  analyze:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Analyze Source Code
          command: docker build . --target analyze

  test:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test Application
          command: docker build . --target test

  build:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build Application
          command: docker build . --target build

workflows:
  make:
    jobs:
      - setup
      - analyze:
          requires:
            - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - setup
