version: 2.1

executors:
  node:
    docker:
      - image: node:17.2.0

commands:
  run-yarn:
    parameters:
      name:
        type: string
      command:
        type: string
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: <<parameters.name>>
          command: yarn <<parameters.command>>

workflows:
  check-build:
    jobs:
      - analyze
      - test
      - build

jobs:
  analyze:
    executor: node
    steps:
      - run-yarn:
          name: Lint Application Files
          command: lint
  test:
    executor: node
    steps:
      - run-yarn:
          name: Run Tests
          command: test
  build:
    executor: node
    steps:
      - run-yarn:
          name: Build Applications
          command: build
