version: 2.1

executors:
  node:
    docker:
      - image: node:17.2.0

commands:
  run_yarn:
    parameters:
      title:
        type: string
      script:
        type: string
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: <<parameters.title>>
          command: yarn <<parameters.script>>

workflows:
  make:
    jobs:
      - analyze
      - test
      - build

jobs:
  analyze:
    executor: node
    steps:
      - run_yarn:
          title: Lint Application Files
          script: lint
  test:
    executor: node
    steps:
      - run_yarn:
          title: Run Tests
          script: test
      - store_artifacts:
          path: reports/coverage
  build:
    executor: node
    steps:
      - run_yarn:
          title: Build Applications
          script: build
